"""group_08_policy_revision

Revision ID: 00fbec50138a
Revises: b0fce6cc6f73
Create Date: 2026-08-30 14:56:35.218191

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import codegate.database.models.analysis

# revision identifiers, used by Alembic.
revision: str = '00fbec50138a'
down_revision: Union[str, Sequence[str], None] = 'b0fce6cc6f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy_engine_version', sa.String(length=50), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('quality_pass_threshold', sa.Float(), nullable=False),
    sa.Column('quality_block_threshold', sa.Float(), nullable=False),
    sa.Column('risk_warning_threshold', sa.Float(), nullable=False),
    sa.Column('risk_block_threshold', sa.Float(), nullable=False),
    sa.Column('max_critical_findings', sa.Integer(), nullable=False),
    sa.Column('max_high_security_findings', sa.Integer(), nullable=False),
    sa.Column('require_quality_score', sa.Boolean(), nullable=False),
    sa.Column('require_risk_score', sa.Boolean(), nullable=False),
    sa.Column('require_complete_quality', sa.Boolean(), nullable=False),
    sa.Column('require_complete_risk', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_policies_id'), 'quality_policies', ['id'], unique=False)
    op.create_index(op.f('ix_quality_policies_repository_id'), 'quality_policies', ['repository_id'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('policy_engine_version', sa.String(length=50), nullable=False),
    sa.Column('policy_revision', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('passed_rules_count', sa.Integer(), nullable=True),
    sa.Column('warning_rules_count', sa.Integer(), nullable=True),
    sa.Column('blocked_rules_count', sa.Integer(), nullable=True),
    sa.Column('breakdown_json', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('flags_json', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('config_snapshot_json', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('evaluation_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('github_check_run_id', sa.Integer(), nullable=True),
    sa.Column('github_publish_status', sa.String(length=50), nullable=True),
    sa.Column('github_publish_error', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['quality_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'policy_id', 'policy_revision', name='uq_policy_evaluation')
    )
    op.create_index(op.f('ix_policy_evaluations_analysis_run_id'), 'policy_evaluations', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_id'), 'policy_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_policy_id'), 'policy_evaluations', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_evaluations_policy_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_analysis_run_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index(op.f('ix_quality_policies_repository_id'), table_name='quality_policies')
    op.drop_index(op.f('ix_quality_policies_id'), table_name='quality_policies')
    op.drop_table('quality_policies')
    # ### end Alembic commands ###
