"""workspace_invitations

Revision ID: 015edf54cf67
Revises: 7423ae9e9c60
Create Date: 2026-08-31 13:40:16.362963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015edf54cf67'
down_revision: Union[str, Sequence[str], None] = '7423ae9e9c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invitee_github_login', sa.String(length=255), nullable=True),
    sa.Column('invitee_email', sa.String(length=255), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], name=op.f('fk_workspace_invitations_inviter_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_workspace_invitations_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_invitations'))
    )
    with op.batch_alter_table('workspace_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_invitations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_id'))

    op.drop_table('workspace_invitations')
    # ### end Alembic commands ###
