"""github_repository_sync

Revision ID: 05369161d78f
Revises: de702518d327
Create Date: 2026-08-31 12:28:18.121237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05369161d78f'
down_revision: Union[str, Sequence[str], None] = 'de702518d327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_sync_error', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_status', sa.String(length=50), nullable=False, server_default='ACTIVE'))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint(batch_op.f('uix_provider_fullname_workspace'), type_='unique')
        batch_op.create_unique_constraint('uix_github_connection_provider_repo_id', ['github_connection_id', 'provider_repository_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_constraint('uix_github_connection_provider_repo_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_provider_fullname_workspace'), ['provider', 'full_name', 'workspace_id'])
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('access_status')

    with op.batch_alter_table('github_connections', schema=None) as batch_op:
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('last_sync_error')
        batch_op.drop_column('last_sync_status')
    # ### end Alembic commands ###
