"""Add Group 04 and 05 models

Revision ID: 263ae425f3cf
Revises: 31ea6c57c62c
Create Date: 2026-08-28 22:38:12.783481

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import codegate
import codegate.database.models.analysis

# revision identifiers, used by Alembic.
revision: str = '263ae425f3cf'
down_revision: Union[str, Sequence[str], None] = '31ea6c57c62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('repository_full_name', sa.String(), nullable=True),
    sa.Column('pull_request_number', sa.Integer(), nullable=True),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'delivery_id', name='uq_webhook_delivery')
    )
    op.create_index(op.f('ix_webhook_events_delivery_id'), 'webhook_events', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.create_table('analyzer_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('analyzer', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('metadata', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyzer_runs_analysis_run_id'), 'analyzer_runs', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_analyzer_runs_analyzer'), 'analyzer_runs', ['analyzer'], unique=False)
    op.create_index(op.f('ix_analyzer_runs_id'), 'analyzer_runs', ['id'], unique=False)
    op.create_table('code_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('analyzer', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('metadata', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_metrics_analysis_run_id'), 'code_metrics', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_code_metrics_analyzer'), 'code_metrics', ['analyzer'], unique=False)
    op.create_index(op.f('ix_code_metrics_file_path'), 'code_metrics', ['file_path'], unique=False)
    op.create_index(op.f('ix_code_metrics_id'), 'code_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_code_metrics_metric_name'), 'code_metrics', ['metric_name'], unique=False)
    op.add_column('findings', sa.Column('is_changed_file', sa.Boolean(), nullable=True))
    op.add_column('findings', sa.Column('is_new_code', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'is_new_code')
    op.drop_column('findings', 'is_changed_file')
    op.drop_index(op.f('ix_code_metrics_metric_name'), table_name='code_metrics')
    op.drop_index(op.f('ix_code_metrics_id'), table_name='code_metrics')
    op.drop_index(op.f('ix_code_metrics_file_path'), table_name='code_metrics')
    op.drop_index(op.f('ix_code_metrics_analyzer'), table_name='code_metrics')
    op.drop_index(op.f('ix_code_metrics_analysis_run_id'), table_name='code_metrics')
    op.drop_table('code_metrics')
    op.drop_index(op.f('ix_analyzer_runs_id'), table_name='analyzer_runs')
    op.drop_index(op.f('ix_analyzer_runs_analyzer'), table_name='analyzer_runs')
    op.drop_index(op.f('ix_analyzer_runs_analysis_run_id'), table_name='analyzer_runs')
    op.drop_table('analyzer_runs')
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_delivery_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
