"""Add AnalysisJob and QUEUED status

Revision ID: 7423ae9e9c60
Revises: 05369161d78f
Create Date: 2026-08-31 13:04:46.294446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7423ae9e9c60'
down_revision: Union[str, Sequence[str], None] = '05369161d78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_analysis_jobs_analysis_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_jobs'))
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_jobs_analysis_run_id'), ['analysis_run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_celery_task_id'), ['celery_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_celery_task_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_analysis_run_id'))

    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
