"""group_10_reviewer_recommendation

Revision ID: 80e3e8c27840
Revises: c37885098272
Create Date: 2026-08-30 15:52:37.716699

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80e3e8c27840'
down_revision: Union[str, Sequence[str], None] = 'c37885098272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_recommendation_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('top_n', sa.Integer(), nullable=False),
    sa.Column('minimum_recommendation_score', sa.Float(), nullable=False),
    sa.Column('history_days', sa.Integer(), nullable=False),
    sa.Column('max_history_commits', sa.Integer(), nullable=False),
    sa.Column('allow_external_codeowners', sa.Boolean(), nullable=False),
    sa.Column('eligible_roles_json', sa.String(length=512), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewer_recommendation_configs_id'), 'reviewer_recommendation_configs', ['id'], unique=False)
    op.create_index(op.f('ix_reviewer_recommendation_configs_repository_id'), 'reviewer_recommendation_configs', ['repository_id'], unique=False)
    op.create_table('reviewer_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('config_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('eligible_candidate_count', sa.Integer(), nullable=False),
    sa.Column('recommended_candidate_count', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('available_weight', sa.Float(), nullable=False),
    sa.Column('missing_sources_json', sa.String(length=1024), nullable=True),
    sa.Column('unresolved_codeowners_json', sa.String(length=4096), nullable=True),
    sa.Column('config_snapshot_json', sa.String(length=4096), nullable=True),
    sa.Column('breakdown_json', sa.String(length=4096), nullable=True),
    sa.Column('error_message', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['config_id'], ['reviewer_recommendation_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'config_id', 'config_revision', 'engine_version', name='uix_reviewer_logical_identity')
    )
    op.create_index(op.f('ix_reviewer_recommendations_analysis_run_id'), 'reviewer_recommendations', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_reviewer_recommendations_id'), 'reviewer_recommendations', ['id'], unique=False)
    op.create_table('reviewer_recommendation_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_username', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('codeowners_score', sa.Float(), nullable=True),
    sa.Column('exact_file_score', sa.Float(), nullable=True),
    sa.Column('directory_score', sa.Float(), nullable=True),
    sa.Column('recency_score', sa.Float(), nullable=True),
    sa.Column('exact_file_commits', sa.Integer(), nullable=False),
    sa.Column('directory_commits', sa.Integer(), nullable=False),
    sa.Column('file_coverage_percent', sa.Float(), nullable=True),
    sa.Column('matched_files_json', sa.String(length=4096), nullable=True),
    sa.Column('reasons_json', sa.String(length=4096), nullable=True),
    sa.Column('evidence_json', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['reviewer_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewer_recommendation_candidates_id'), 'reviewer_recommendation_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_reviewer_recommendation_candidates_recommendation_id'), 'reviewer_recommendation_candidates', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewer_recommendation_candidates_recommendation_id'), table_name='reviewer_recommendation_candidates')
    op.drop_index(op.f('ix_reviewer_recommendation_candidates_id'), table_name='reviewer_recommendation_candidates')
    op.drop_table('reviewer_recommendation_candidates')
    op.drop_index(op.f('ix_reviewer_recommendations_id'), table_name='reviewer_recommendations')
    op.drop_index(op.f('ix_reviewer_recommendations_analysis_run_id'), table_name='reviewer_recommendations')
    op.drop_table('reviewer_recommendations')
    op.drop_index(op.f('ix_reviewer_recommendation_configs_repository_id'), table_name='reviewer_recommendation_configs')
    op.drop_index(op.f('ix_reviewer_recommendation_configs_id'), table_name='reviewer_recommendation_configs')
    op.drop_table('reviewer_recommendation_configs')
    # ### end Alembic commands ###
