"""Add unique constraint for provider and provider_user_id

Revision ID: 89cdc482f0db
Revises: d8b5b93fa8af
Create Date: 2026-08-31 10:24:08.255961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89cdc482f0db'
down_revision: Union[str, Sequence[str], None] = 'd8b5b93fa8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_provider_provider_user_id', ['provider', 'provider_user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uix_provider_provider_user_id', type_='unique')

    # ### end Alembic commands ###
