"""tenant_isolation

Revision ID: a33147b1ecb9
Revises: 89cdc482f0db
Create Date: 2026-08-31 10:39:06.308534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33147b1ecb9'
down_revision: Union[str, Sequence[str], None] = '89cdc482f0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_github_connections_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_github_connections_workspace_id_teams'), 'teams', ['workspace_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uix_provider_full_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_repositories_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_unique_constraint('uix_provider_fullname_workspace', ['provider', 'full_name', 'workspace_id'])
        batch_op.create_foreign_key(batch_op.f('fk_repositories_workspace_id_teams'), 'teams', ['workspace_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_repositories_workspace_id_teams'), type_='foreignkey')
        batch_op.drop_constraint('uix_provider_fullname_workspace', type_='unique')
        batch_op.drop_index(batch_op.f('ix_repositories_workspace_id'))
        batch_op.create_unique_constraint(batch_op.f('uix_provider_full_name'), ['provider', 'full_name'])
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('github_connections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_github_connections_workspace_id_teams'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_github_connections_workspace_id'))
        batch_op.drop_column('workspace_id')

    # ### end Alembic commands ###
