"""Add RiskScore model

Revision ID: b0fce6cc6f73
Revises: f7ff7f175678
Create Date: 2026-08-29 10:21:46.583204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import codegate.database.models.analysis


# revision identifiers, used by Alembic.
revision: str = 'b0fce6cc6f73'
down_revision: Union[str, Sequence[str], None] = 'f7ff7f175678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('overall_risk', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('change_surface_risk', sa.Float(), nullable=True),
    sa.Column('sensitive_path_risk', sa.Float(), nullable=True),
    sa.Column('security_risk', sa.Float(), nullable=True),
    sa.Column('complexity_risk', sa.Float(), nullable=True),
    sa.Column('available_weight', sa.Float(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('missing_dimensions', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('breakdown_json', codegate.database.models.analysis.JSONType(), nullable=False),
    sa.Column('calculation_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'calculation_version', name='uq_risk_score_version')
    )
    op.create_index(op.f('ix_risk_scores_analysis_run_id'), 'risk_scores', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_analysis_run_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    # ### end Alembic commands ###
