"""Group 09 testing support

Revision ID: c37885098272
Revises: 00fbec50138a
Create Date: 2026-08-30 15:17:02.846774

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import codegate.database.models.analysis

# revision identifiers, used by Alembic.
revision: str = 'c37885098272'
down_revision: Union[str, Sequence[str], None] = '00fbec50138a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('executor_type', sa.String(length=50), nullable=False),
    sa.Column('working_directory', sa.String(length=255), nullable=True),
    sa.Column('test_paths_json', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('pytest_args_json', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('coverage_enabled', sa.Boolean(), nullable=False),
    sa.Column('coverage_source_json', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('docker_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id')
    )
    op.create_table('test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('test_configuration_id', sa.Integer(), nullable=True),
    sa.Column('runner_version', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('executor_type', sa.String(length=50), nullable=False),
    sa.Column('execution_status', sa.String(length=50), nullable=False),
    sa.Column('test_outcome', sa.String(length=50), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('tests_total', sa.Integer(), nullable=False),
    sa.Column('tests_passed', sa.Integer(), nullable=False),
    sa.Column('tests_failed', sa.Integer(), nullable=False),
    sa.Column('tests_skipped', sa.Integer(), nullable=False),
    sa.Column('tests_errors', sa.Integer(), nullable=False),
    sa.Column('tests_xfailed', sa.Integer(), nullable=True),
    sa.Column('tests_xpassed', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('stdout_excerpt', sa.String(), nullable=True),
    sa.Column('stderr_excerpt', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_configuration_id'], ['test_configurations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id')
    )
    op.create_table('coverage_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_run_id', sa.Integer(), nullable=False),
    sa.Column('coverage_version', sa.String(length=50), nullable=False),
    sa.Column('line_coverage', sa.Float(), nullable=True),
    sa.Column('branch_coverage', sa.Float(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('covered_lines', sa.Integer(), nullable=False),
    sa.Column('missing_lines', sa.Integer(), nullable=False),
    sa.Column('changed_line_coverage', sa.Float(), nullable=True),
    sa.Column('changed_total_lines', sa.Integer(), nullable=False),
    sa.Column('changed_covered_lines', sa.Integer(), nullable=False),
    sa.Column('changed_missing_lines', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('breakdown_json', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_run_id')
    )
    op.add_column('quality_policies', sa.Column('test_gate_enabled', sa.Boolean(), nullable=False))
    op.add_column('quality_policies', sa.Column('require_tests', sa.Boolean(), nullable=False))
    op.add_column('quality_policies', sa.Column('coverage_gate_enabled', sa.Boolean(), nullable=False))
    op.add_column('quality_policies', sa.Column('require_coverage', sa.Boolean(), nullable=False))
    op.add_column('quality_policies', sa.Column('changed_coverage_warning_threshold', sa.Float(), nullable=False))
    op.add_column('quality_policies', sa.Column('changed_coverage_block_threshold', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quality_policies', 'changed_coverage_block_threshold')
    op.drop_column('quality_policies', 'changed_coverage_warning_threshold')
    op.drop_column('quality_policies', 'require_coverage')
    op.drop_column('quality_policies', 'coverage_gate_enabled')
    op.drop_column('quality_policies', 'require_tests')
    op.drop_column('quality_policies', 'test_gate_enabled')
    op.drop_table('coverage_reports')
    op.drop_table('test_runs')
    op.drop_table('test_configurations')
    # ### end Alembic commands ###
