"""github_installation_states

Revision ID: de702518d327
Revises: 55c6ed77ad16
Create Date: 2026-08-31 12:05:28.057166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de702518d327'
down_revision: Union[str, Sequence[str], None] = '55c6ed77ad16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_github_installation_states_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['teams.id'], name=op.f('fk_github_installation_states_workspace_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_installation_states'))
    )
    with op.batch_alter_table('github_installation_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_installation_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_installation_states_state_hash'), ['state_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_github_installation_states_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_installation_states_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('github_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repository_selection', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_connections', schema=None) as batch_op:
        batch_op.drop_column('repository_selection')
    with op.batch_alter_table('github_installation_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_installation_states_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_github_installation_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_github_installation_states_state_hash'))
        batch_op.drop_index(batch_op.f('ix_github_installation_states_id'))

    op.drop_table('github_installation_states')
    # ### end Alembic commands ###
