"""add_test_config_fields

Revision ID: e1f832676b73
Revises: 015edf54cf67
Create Date: 2026-09-01 20:32:35.064359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f832676b73'
down_revision: Union[str, Sequence[str], None] = '015edf54cf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('install_command', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('test_command', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('network_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_configurations', schema=None) as batch_op:
        batch_op.drop_column('network_enabled')
        batch_op.drop_column('test_command')
        batch_op.drop_column('install_command')

    # ### end Alembic commands ###
