"""Add GitHubConnection and data mode

Revision ID: f18d4f8fc6ca
Revises: 80e3e8c27840
Create Date: 2026-08-30 19:22:51.030377

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f18d4f8fc6ca'
down_revision: Union[str, Sequence[str], None] = '80e3e8c27840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('installation_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_connections'))
    )
    with op.batch_alter_table('github_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_connections_id'), ['id'], unique=False)

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_source', sa.String(length=20), server_default='LIVE', nullable=False))
        batch_op.add_column(sa.Column('github_connection_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_repositories_github_connection_id_github_connections'), 'github_connections', ['github_connection_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_repositories_github_connection_id_github_connections'), type_='foreignkey')
        batch_op.drop_column('github_connection_id')
        batch_op.drop_column('data_source')

    with op.batch_alter_table('github_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_connections_id'))

    op.drop_table('github_connections')
    # ### end Alembic commands ###
