"""Add Quality Score model

Revision ID: f7ff7f175678
Revises: 263ae425f3cf
Create Date: 2026-08-28 23:23:06.786415

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import codegate.database.models.analysis

# revision identifiers, used by Alembic.
revision: str = 'f7ff7f175678'
down_revision: Union[str, Sequence[str], None] = '263ae425f3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('code_quality_score', sa.Float(), nullable=True),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('testing_score', sa.Float(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('maintainability_score', sa.Float(), nullable=True),
    sa.Column('ai_review_score', sa.Float(), nullable=True),
    sa.Column('available_weight', sa.Float(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('missing_dimensions', codegate.database.models.analysis.JSONType(), nullable=True),
    sa.Column('breakdown_json', codegate.database.models.analysis.JSONType(), nullable=False),
    sa.Column('calculation_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'calculation_version', name='uq_quality_score_version')
    )
    op.create_index(op.f('ix_quality_scores_analysis_run_id'), 'quality_scores', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_quality_scores_id'), 'quality_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_scores_id'), table_name='quality_scores')
    op.drop_index(op.f('ix_quality_scores_analysis_run_id'), table_name='quality_scores')
    op.drop_table('quality_scores')
    # ### end Alembic commands ###
