import copy
from typing import Dict, Any, Optional
from pydantic import BaseModel
from pr_agent.tools.pr_reviewer import PRReviewer

class CodeGateAdapter:
    """
    Adapter that wraps PR-Agent's PRReviewer to intercept the structured AI output
    while allowing the original PR-Agent pipeline to continue and publish to GitHub.
    """
    def __init__(self, pr_url: str, reviewer: Optional[PRReviewer] = None):
        self.pr_url = pr_url
        self.reviewer = reviewer if reviewer is not None else PRReviewer(pr_url)
        self.captured_structured_data: Optional[Dict[str, Any]] = None
        self._monkey_patch_structured_publisher()

    def _monkey_patch_structured_publisher(self):
        """
        Intercepts `publish_structured_review` which PR-Agent uses to output the raw YAML 
        parsed dictionary. We grab a deep copy of this data before it is possibly mutated
        or discarded, then pass it to the original publisher if one exists.
        """
        original_publisher = getattr(self.reviewer.git_provider, "publish_structured_review", None)
        
        def mock_publisher(data: dict):
            # Capture the data exactly as it was generated by the AI parser
            self.captured_structured_data = copy.deepcopy(data)
            
            # Call original publisher so we don't break existing PR-Agent hooks
            if callable(original_publisher):
                original_publisher(data)

        self.reviewer.git_provider.publish_structured_review = mock_publisher

    async def run(self) -> Dict[str, Any]:
        """
        Executes the PR-Agent review pipeline and returns the structured data.
        """
        # This will run the AI review and trigger publish_structured_review internally
        await self.reviewer.run()
        
        if self.captured_structured_data is None:
            # If for some reason structured data wasn't captured, return empty or raise
            raise ValueError(f"Failed to capture structured review data for PR {self.pr_url}")
            
        return self.captured_structured_data
