POLICY_ENGINE_VERSION = "policy-v1"

# Default configuration for a repository policy
DEFAULT_QUALITY_PASS_THRESHOLD = 80.0
DEFAULT_QUALITY_BLOCK_THRESHOLD = 60.0

DEFAULT_RISK_WARNING_THRESHOLD = 40.0
DEFAULT_RISK_BLOCK_THRESHOLD = 70.0

DEFAULT_MAX_CRITICAL_FINDINGS = 0
DEFAULT_MAX_HIGH_SECURITY_FINDINGS = 0

DEFAULT_REQUIRE_QUALITY_SCORE = False
DEFAULT_REQUIRE_RISK_SCORE = False

DEFAULT_REQUIRE_COMPLETE_QUALITY = False
DEFAULT_REQUIRE_COMPLETE_RISK = False

# Stable Rule IDs
RULE_ID_MIN_QUALITY_SCORE = "MIN_QUALITY_SCORE"
RULE_ID_QUALITY_COMPLETENESS = "QUALITY_COMPLETENESS"
RULE_ID_QUALITY_AVAILABILITY = "QUALITY_AVAILABILITY"

RULE_ID_MAX_RISK_SCORE = "MAX_RISK_SCORE"
RULE_ID_RISK_COMPLETENESS = "RISK_COMPLETENESS"
RULE_ID_RISK_AVAILABILITY = "RISK_AVAILABILITY"

RULE_ID_MAX_CRITICAL_FINDINGS = "MAX_CRITICAL_FINDINGS"
RULE_ID_MAX_HIGH_SECURITY_FINDINGS = "MAX_HIGH_SECURITY_FINDINGS"
